<?xml version="1.0"?>
<!DOCTYPE students SYSTEM "students.dtd">    <!--外部引入 -->
<!-- <!DOCTYPE sutdents [                     //內部宣告 
        <!ELEMENT students (student*)>
        <!ELEMENT student (age, name)>  
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ATTLIST student number ID #REQUIRED>
    ]>
-->
<students>
    <student number="s1">
        <age>21</age>
        <name>John</name>
    </student>
    <student number="s2">
        <age>22</age>
        <name>Mary</name>
    </student>
</students>